import type { CountryConfig } from "./types";

export const COUNTRY_CONFIGS: CountryConfig[] = [
  {
    code: "US",
    name: "United States",
    flag: "US",
    currency: "USD",
    currencySymbol: "$",
    locale: "en-US",
    loanRateRange: { min: 5, max: 8, defaultRate: 6.5 },
    consumptionTax: { label: "Sales Tax", defaultRate: 7.5 },
    gratuitySupported: false,
    retirementPlanLabel: "401(k)",
    retirementDefaultRate: 8,
    taxRegimes: ["default"],
  },
  {
    code: "IN",
    name: "India",
    flag: "IN",
    currency: "INR",
    currencySymbol: "Rs",
    locale: "en-IN",
    loanRateRange: { min: 7, max: 10, defaultRate: 8.2 },
    consumptionTax: { label: "GST", defaultRate: 18 },
    gratuitySupported: true,
    retirementPlanLabel: "EPF",
    retirementDefaultRate: 12,
    taxRegimes: ["old", "new"],
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "GB",
    currency: "GBP",
    currencySymbol: "GBP",
    locale: "en-GB",
    loanRateRange: { min: 4, max: 7, defaultRate: 5.4 },
    consumptionTax: { label: "VAT", defaultRate: 20 },
    gratuitySupported: false,
    retirementPlanLabel: "Workplace Pension",
    retirementDefaultRate: 5,
    taxRegimes: ["default"],
  },
  {
    code: "CA",
    name: "Canada",
    flag: "CA",
    currency: "CAD",
    currencySymbol: "CAD",
    locale: "en-CA",
    loanRateRange: { min: 4.5, max: 8, defaultRate: 6.1 },
    consumptionTax: { label: "VAT", defaultRate: 13 },
    gratuitySupported: false,
    retirementPlanLabel: "RRSP Estimate",
    retirementDefaultRate: 8,
    taxRegimes: ["default"],
  },
  {
    code: "AU",
    name: "Australia",
    flag: "AU",
    currency: "AUD",
    currencySymbol: "AUD",
    locale: "en-AU",
    loanRateRange: { min: 5, max: 8.5, defaultRate: 6.4 },
    consumptionTax: { label: "VAT", defaultRate: 10 },
    gratuitySupported: false,
    retirementPlanLabel: "Superannuation",
    retirementDefaultRate: 11,
    taxRegimes: ["default"],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "AE",
    currency: "AED",
    currencySymbol: "AED",
    locale: "en-AE",
    loanRateRange: { min: 3.5, max: 7.5, defaultRate: 5.8 },
    consumptionTax: { label: "VAT", defaultRate: 5 },
    gratuitySupported: true,
    retirementPlanLabel: "Savings Plan",
    retirementDefaultRate: 8,
    taxRegimes: ["default"],
  },
  {
    code: "DE",
    name: "Germany",
    flag: "DE",
    currency: "EUR",
    currencySymbol: "EUR",
    locale: "de-DE",
    loanRateRange: { min: 3, max: 6.5, defaultRate: 4.8 },
    consumptionTax: { label: "VAT", defaultRate: 19 },
    gratuitySupported: false,
    retirementPlanLabel: "Pension Estimate",
    retirementDefaultRate: 7,
    taxRegimes: ["default"],
  },
];

export const COUNTRY_MAP = Object.fromEntries(COUNTRY_CONFIGS.map((country) => [country.code, country]));